services:
  titanic-app:
    build: .
    ports:
      - "${DOCKER_EXTERNAL_PORT:-8501}:${STREAMLIT_SERVER_PORT:-8501}"
    environment:
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS:-0.0.0.0}
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-8501}
      - STREAMLIT_SERVER_HEADLESS=${STREAMLIT_SERVER_HEADLESS:-true}
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=${STREAMLIT_BROWSER_GATHER_USAGE_STATS:-false}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE:-1}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./model:/app/model
    restart: unless-stopped
    container_name: titanic-ml-app